version: 2
jobs:
  build:
    machine: true

    working_directory: ~/Cashier-BTC

    steps:
      - checkout

      - run:
          command: |
            echo Setting up
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs couchdb
            npm install
            cp config.js.dev config.js
            curl http://127.0.0.1:5984/ || true
            curl -s -X PUT http://localhost:5984/_config/admins/user -d '"pass"' || true
            curl -s -X PUT http://user:pass@localhost:5984/cashier-btc || true
            cd ~/Cashier-BTC
            wget https://bitcoin.org/bin/bitcoin-core-0.15.0.1/bitcoin-0.15.0.1-x86_64-linux-gnu.tar.gz
            tar -xvf  bitcoin-0.15.0.1-x86_64-linux-gnu.tar.gz

      - run:
          name: Running bitcoind in background...
          command: ~/Cashier-BTC/bitcoin-0.15.0/bin/bitcoind -rpcuser=user  -rpcpassword=pass -rpcbind=0.0.0.0  -rpcallowip=127.0.0.1 -datadir=/tmp/
          background: true

      - run: sleep 30

      - run: cd ~/Cashier-BTC; npm test


